NJSim/Quora_Clone

express-project-starter/app.js
express-project-starter/package-lock.json
express-project-starter/routes/users.js
express-project-starter/views/user-login.pug

finished login page and finished making respectful .pug file

finished user login page w/ pug

---

express-project-starter/auth.js
express-project-starter/db/seeders/20210921162049-addUsers.js
express-project-starter/db/seeders/20210921162739-addQuestions.js
express-project-starter/db/seeders/20210921162852-addAnswers.js
express-project-starter/routes/users.js

Seeder files

---

express-project-starter/public/javascripts/index.js
express-project-starter/public/stylesheets/index.css
express-project-starter/routes/index.js
express-project-starter/views/layout.pug
express-project-starter/views/question-detail.pug

add some css

---

express-project-starter/public/javascripts/index.js

solve the logout drop down, I will talk about this part tomorrow morning.

resolve logout

---

express-project-starter/public/javascripts/index.js
express-project-starter/views/layout.pug
express-project-starter/views/my-answers.pug

drop down lists

---

public/javascripts/index.js
routes/index.js
views/layout.pug

search functionality

---

views/my-answers.pug
views/my-questions.pug

ask approve for add link of questions

add link of question

---

public/javascripts/index.js
public/stylesheets/index.css
views/index.pug
views/question-detail.pug

add answer in the main page

---

public/javascripts/index.js
routes/index.js
views/my-answers.pug

delete answer and refresh page

Add answer

---

db/models/answer.js
db/models/question.js
public/javascripts/index.js
routes/index.js

delete question and answer

---

public/stylesheets/index.css
views/index.pug
views/layout.pug

css on home page

---

views/index.pug

commented out delete button on main page

small delete button changes

---

public/javascripts/index.js
public/stylesheets/index.css
views/index.pug
views/my-answers.pug
views/my-questions.pug
views/question-detail.pug

nav bar fix & comment has icon now with bubbling working

nav bar fix & comment has icon now with bubbling working

---

public/javascripts/index.js
public/stylesheets/index.css
routes/index.js
views/question-detail.pug

Edit question

---

public/javascripts/index.js
public/stylesheets/answers.css
routes/index.js
views/my-answers.pug

fix bug at my answers page

---

public/stylesheets/answers.css
public/stylesheets/questions.css
routes/index.js
views/index.pug
views/my-answers.pug
views/question-detail.pug
views/user-login.pug
views/user-signup.pug

fixed post question and answer content css on 1 page

---

public/stylesheets/index.css
views/layout.pug

CSS profile page edit

---

public/stylesheets/index.css
public/stylesheets/nav.css
public/stylesheets/questions.css

fixed css h1 tags centered - changed main body to flex instead of grid. changed some padding on left nav bar

css changes - fixed a lot and editted h1 tags

---

public/javascripts/index.js
public/stylesheets/questions.css
public/stylesheets/story.css
views/layout.pug
views/our-story.pug
views/question-detail.pug

fixed edit questions

---

README.md

read me file wip

---

public/stylesheets/questions.css
routes/index.js
views/index.pug
views/my-answers.pug
views/my-questions.pug
views/question-detail.pug

add date on all pages

---

db/seeders/20210921162049-addUsers.js
db/seeders/20210921162739-addQuestions.js
db/seeders/20210921162852-addAnswers.js
db/seeders/20210922222952-addQuestions_votes.js
db/seeders/20210922223010-addAnswers_votes.js

Added example seeders for users, questions, answers, q_votes, and a_votes

added example seeders

---

db/seeders/20210921162049-addUsers.js
routes/index.js
routes/users.js

final changes- changed demoUser

---

routes/index.js
views/index.pug

solve home page answers order descending issue

solve home page answers order issue

---

public/javascripts/index.js
views/index.pug

solve double click issue on all pages

solve double click issue on all pages
